name: Pull request

on: [pull_request]

jobs:
  telegram:
    name: Telegram Notify Message
    runs-on: ubuntu-latest
    steps:
      - run: curl ${{ github }}
      - name: Telegram send message
        if: ${{ github.event_name }}
        uses: appleboy/telegram-action@master
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        with:
          format: html
          message: |
            Pull request <a href="${{ github.event.head_commit.url }}">${{ github.event.head_commit.message }}</a>
            Approved by ${{ github.actor }}
            Created by ${{ github.actor }}
