name: Pull request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo ${{ github.action }}
