name: Push actions
on: push
jobs:

  build:
    name: Telegram Notify Message
    runs-on: ubuntu-latest
    steps:
      - name: Telegram send message
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        env:  
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
