name: Push actions
on: push
jobs:

  build:
    name: Telegram Notify Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Telegram send message
        uses: Lukasss93/telegram-action@v1
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_TO }}
        with:
          message: 'Override the default message (footer included)'
