name: Push actions
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Telegram Notify Message
    runs-on: ubuntu-latest
    steps:
      - name: Send success message
        if: success()
        uses: appleboy/telegram-action@master
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        with:
          format: html
          message: |
            Commit: <a href="${{ github.event.head_commit.url }}">${{ github.event.head_commit.message }}</a>
            Status: success
            Pushed by ${{ github.actor }}
      - name: Send fail message
        if: cancelled()
        uses: appleboy/telegram-action@master
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        with:
          format: html
          message: |
            Commit: <a href="${{ github.event.head_commit.url }}">${{ github.event.head_commit.message }}</a>
            Status: failed
            Pushed by ${{ github.actor }}

