name: Telegram Notification
on:
  push:
    branches: 
      - master
jobs:

  build:
    name: Telegram send message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Telegram Notify Message
        run: curl https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_TO }}&text=Commit ${{ github.sha }}%20pushed%20by%20${{ github.actor }}%20on%20${{ github.ref }}
