name: Telegram Notification
on:
  push:
    branches: 
      - master
jobs:

  build:
    name: Telegram send message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Telegram Notify Message
        run: curl https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_TO }}&text=Testing%20if%20this%20worksCommit ${{ github.sha }} pushed by ${{ github.actor }} on ${{ github.ref }}
